In [1]:
import numpy as np
import torch

In [4]:
a=torch.ones((3,))

In [5]:
a.dim()

1

In [6]:
b = torch.tensor(1)
b.dim()

0

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
for i in range(-1, 10):
    print(i)

-1
0
1
2
3
4
5
6
7
8
9


In [2]:
import torch.nn.functional as F
import torch.nn as nn
import torch

In [7]:
x = torch.tensor([3, 4])
F.one_hot(x, num_classes=5)

tensor([[0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])