In [1]:
import sys
sys.path.append('../..')
from MPRA_predict.utils import *
from MPRA_predict.datasets import *

np.set_printoptions(suppress=True, precision=6)

In [2]:
bed_df = pd.read_csv('data/enformer_data.csv')
bed_df

chr      start        end  split
0      chr18     928386    1059458  train
1       chr4  113630947  113762019  train
2      chr11   18427720   18558792  train
3      chr16   85805681   85936753  train
4       chr3  158386188  158517260  train
...      ...        ...        ...    ...
38166  chr19   33204702   33335774   test
38167  chr14   41861379   41992451   test
38168  chr19   30681544   30812616   test
38169  chr14   61473198   61604270   test
38170   chr2  129664471  129795543   test

[38171 rows x 4 columns]

In [3]:
preds = np.load('data/Enformer_test_pred_196608.npy')
preds = preds[:, :, [121,122,123,625]]
print(preds.shape)
print(preds)

(1937, 896, 4)
[[[0.016335 0.028433 0.029726 0.004304]
  [0.030148 0.049239 0.037334 0.007469]
  [0.025005 0.044172 0.041899 0.003629]
  ...
  [0.040047 0.049018 0.028312 0.079748]
  [0.042089 0.051732 0.029508 0.100062]
  [0.043921 0.05195  0.027163 0.119398]]

 [[0.007733 0.012303 0.019261 0.000803]
  [0.009892 0.016405 0.022584 0.000194]
  [0.011623 0.020164 0.024905 0.000189]
  ...
  [0.014618 0.019595 0.025875 0.000387]
  [0.011427 0.015811 0.020052 0.003146]
  [0.013619 0.016331 0.017059 0.004749]]

 [[0.030212 0.045744 0.036128 0.033451]
  [0.042736 0.058777 0.038215 0.074201]
  [0.063972 0.081136 0.045197 0.128831]
  ...
  [0.018519 0.028365 0.034018 0.006832]
  [0.012106 0.020531 0.026289 0.000918]
  [0.016829 0.028573 0.026081 0.000659]]

 ...

 [[0.028158 0.037469 0.022155 0.047254]
  [0.021289 0.030038 0.019911 0.030421]
  [0.027023 0.035911 0.021137 0.042069]
  ...
  [0.043415 0.06443  0.027173 0.080854]
  [0.041947 0.070768 0.027731 0.066529]
  [0.045271 0.09338  0.035774

In [4]:
targets = np.load('data/enformer_test_targets.npy')

print(targets.shape)
print(targets)

(1937, 896, 5313)
[[[0.042084 0.049835 0.011589 ... 0.       0.       0.      ]
  [0.053009 0.041687 0.049561 ... 0.       0.       0.      ]
  [0.052582 0.010979 0.012878 ... 0.       0.       0.      ]
  ...
  [0.09314  0.156006 0.322021 ... 0.       0.       0.      ]
  [0.07489  0.083801 0.233032 ... 0.       0.       0.      ]
  [0.113281 0.130249 0.169922 ... 0.       0.       0.      ]]

 [[0.038696 0.003653 0.       ... 0.       0.       0.      ]
  [0.039612 0.048767 0.004505 ... 0.       0.       0.      ]
  [0.049225 0.080994 0.018021 ... 0.       0.       0.096191]
  ...
  [0.045441 0.089905 0.073364 ... 0.       0.       0.      ]
  [0.052673 0.051666 0.       ... 0.       0.       0.116455]
  [0.089111 0.042511 0.066956 ... 0.       0.       0.      ]]

 [[0.042511 0.05722  0.       ... 0.       0.       0.      ]
  [0.034882 0.015022 0.       ... 0.       0.       0.      ]
  [0.055511 0.065857 0.037323 ... 0.       0.       0.      ]
  ...
  [0.03717  0.023071 0.020599 

In [5]:
# labels = []
# label = np.load('data/labels_track_index_121.npy')
# labels.append(label)
# label = np.load('data/labels_track_index_122.npy')
# labels.append(label)
# label = np.load('data/labels_track_index_123.npy')
# labels.append(label)
# label = np.load('data/labels_track_index_625.npy')
# labels.append(label)
# labels = np.stack(labels, axis=-1)

# labels = labels[test_indices]
# print(labels.shape)
# print(labels)

In [6]:
# def soft_clip(values, tc):
#     clipped_values = np.minimum(values, tc + np.sqrt(np.maximum(0, values - tc)))
#     return clipped_values
# targets = soft_clip(targets, 32)

In [7]:
# 计算每个特征通道的相关性系数
corr = np.zeros(preds.shape[2])
for i in range(preds.shape[2]):
    # pred_0 = preds[:, :, 0].reshape(-1)
    # label_0 = labels[:, :, 0].reshape(-1)

    pred = preds[0, :, i].reshape(-1)  # 获取第 c 个特征通道的预测值，并展平成 N*L
    target = targets[0, :, i].reshape(-1)  # 获取第 c 个特征通道的标签值，并展平成 N*L

    r, _ = pearsonr(pred, target)
    print(r)
    # r, _ = pearsonr(pred, pred_0)
    # print(r)
    # r, _ = pearsonr(label, label_0)
    # print(r)

0.5238110172766144
0.4385378810291334
0.19371280658877804
0.3375181754502906


In [8]:
targets = pd.read_csv('/home/shared/enformer_data/human/targets.txt', sep='\t')
targets_K562 = targets[targets['description'] == 'DNASE:K562']
targets_K562

index  genome   identifier  \
121    121       0  ENCFF413AHU   
122    122       0  ENCFF868NHV   
123    123       0  ENCFF565YDB   
625    625       0  ENCFF971AHO   

                                                  file  clip  scale sum_stat  \
121  /home/drk/tillage/datasets/human/dnase/encode/...    32      2     mean   
122  /home/drk/tillage/datasets/human/dnase/encode/...    32      2     mean   
123  /home/drk/tillage/datasets/human/dnase/encode/...    32      2     mean   
625  /home/drk/tillage/datasets/human/dnase/encode/...    32      2     mean   

    description  
121  DNASE:K562  
122  DNASE:K562  
123  DNASE:K562  
625  DNASE:K562

In [9]:
y_pred = np.load('data/Enformer_Siraj_pred_len=196608.npy')
print(y_pred.shape)

(1937, 896, 5313)
