In [1]:
import os
import torch
import numpy as np
import pandas as pd
import sys
sys.path.append('..')
from MPRA_predict.utils import *
from MPRA_predict.metrics import *

ModuleNotFoundError: No module named 'MPRA_predict'

In [6]:
def merge_npy_files(files_dir, files_prefix, output_file):
    """
    合并多个 .npy 文件并保存为一个文件。

    :param files_dir: 存放 .npy 文件的目录
    :param files_prefix: 保存文件的前缀，比如 'Enformer_Siraj_pred_part'
    :param output_file: 合并后保存的文件名
    """
    # 找到所有符合前缀的 .npy 文件
    file_list = sorted([f for f in os.listdir(files_dir) if f.startswith(files_prefix) and f.endswith('.npy')])

    if not file_list:
        print("No files found with the given prefix!")
        return

    # 初始化一个空的列表来存放所有部分数据
    merged_data = []

    for file in file_list:
        file_path = os.path.join(files_dir, file)
        print(f'Loading {file_path}')
        data = np.load(file_path)
        merged_data.append(data)

    # 将所有部分数据拼接成一个大数组
    merged_data = np.concatenate(merged_data, axis=0)

    # 确保输出文件的完整路径
    output_path = os.path.join(files_dir, output_file)

    # 保存合并后的数据到新的 .npy 文件
    np.save(output_path, merged_data)
    print(f"All files merged and saved to {output_path}")



merge_npy_files('data', 'Enformer_Siraj_pred_part', 'Enformer_Siraj_pred_all.npy')

In [3]:
f0 = np.load('data/Enformer_Siraj_pred_all_200.npy')
f0[0].mean(0)

array([0.18225816, 0.23097768, 0.28722847, ..., 0.03399419, 0.07661163,
       0.14517386], dtype=float32)

In [4]:
f1 = np.load('data/Enformer_Siraj_pred_256.npy')
f1[0].mean(0)

array([0.1552077 , 0.18577066, 0.24951428, ..., 0.0444698 , 0.06986648,
       0.1880454 ], dtype=float32)

In [5]:
f2 = np.load('data/Enformer_Siraj_pred_196608.npy')
f2[0].mean(0)

array([0.08149792, 0.0595834 , 0.08398052, ..., 0.03100194, 0.33120534,
       0.05567969], dtype=float32)

In [6]:
f3 = np.load('data/Enformer_Siraj_pred_all_256.npy')
f3[0].mean(0)

array([0.15517054, 0.18572146, 0.24941607, ..., 0.04441018, 0.06986722,
       0.18794422], dtype=float32)

In [7]:
f4 = np.load('data/Enformer_Siraj_pred_512.npy')
f4[0].mean(0)

array([0.14751925, 0.17848201, 0.25576484, ..., 0.0628978 , 0.184787  ,
       0.30512774], dtype=float32)

In [8]:
f5 = np.load('data/Enformer_Siraj_pred_random_256_0.npy')
f5[0].mean(0)

array([0.18457259, 0.23168151, 0.3205341 , ..., 0.0258045 , 0.0878814 ,
       0.14335236], dtype=float32)

In [9]:
f6 = np.load('data/Enformer_Siraj_pred_random_256_1.npy')
f6[0].mean(0)

array([0.19631377, 0.24610853, 0.36514908, ..., 0.02263626, 0.07708836,
       0.14065497], dtype=float32)

In [10]:
f7 = np.load('data/Enformer_Siraj_pred_random_256_2.npy')
f7[0].mean(0)

array([0.20343414, 0.2651039 , 0.3828038 , ..., 0.02811209, 0.07859381,
       0.17197105], dtype=float32)

In [19]:
f8 = (f5 + f6 + f7) / 3
f8[0].mean(0)

array([0.1947735 , 0.2476313 , 0.3561623 , ..., 0.02551762, 0.08118786,
       0.1519928 ], dtype=float32)

In [23]:
r = pearson(f0[:160].mean(1).reshape(-1), f1[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f2[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f3[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f4[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f5[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f6[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f7[:160].mean(1).reshape(-1))
print(r)
r = pearson(f0[:160].mean(1).reshape(-1), f8[:160].mean(1).reshape(-1))
print(r)


0.8965479029150073
0.4060833421812523
0.8965552383455654
0.680348792250925
0.9467930646101872
0.9375813623946999
0.9400493824932699
0.9592113984231165


In [24]:
r = pearson(f1[:160].mean(1).reshape(-1), f8[:160].mean(1).reshape(-1))
print(r)

0.9114097033708313
